import { WorkType } from "./types";

export const worksData: WorkType[] = [
  {
    id: 4,
    title: "CareDesk",
    description: "社内問い合わせの対応状況と履歴を一元管理するヘルプデスクアプリ",
    thumbnail: "/images/previewImage/caredesk_dashboard.png",
    previewImage: [
      "/images/previewImage/caredesk_dashboard.png",
      "/images/previewImage/caredesk_ticket-detail.png",
      "/images/previewImage/caredesk_input-assist.png",
      "/images/previewImage/caredesk_employee-view.png",
    ],
    tags: ["Python", "FastAPI", "JavaScript", "SQLite"],
    details: {
      overviews: [
        "社内の問い合わせを、担当者・対応状況・期限・履歴とあわせて一元管理するヘルプデスクアプリです。",
        "登録から解決までの業務フローを整理し、期限超過や停滞案件、初回回答・解決時間をダッシュボードで可視化します。",
        "デモは登録不要で操作できます。初回アクセス時は、起動に時間がかかる場合があります。",
      ],
      features: [
        "問い合わせの登録・検索と、担当者・ステータス・緊急度・対応期限の管理",
        "未解決・期限超過・停滞の件数と、初回回答・解決時間の可視化",
        "公開コメント・社内メモ・変更履歴と、更新を知らせる画面内通知",
        "デモユーザーの切り替えによる、一般社員・ヘルプデスク・管理者の閲覧・操作範囲の出し分け",
        "キーワードと文字列の類似度による、カテゴリ・緊急度・解決済み事例の入力アシスト",
      ],
      technologies: [
        "Python",
        "FastAPI",
        "Pydantic",
        "SQLite",
        "JavaScript",
        "HTML",
        "CSS",
        "GitHub Actions",
        "Render",
      ],
      github: "https://github.com/hiro774/caredesk",
      website: "https://caredesk-sbae.onrender.com/",
    },
  },
  {
    id: 3,
    title: "Mlb Report AI",
    description: "OPENAI-APIとRAGを活用した会話型Line Bot",
    thumbnail: "/images/thumbnail/mlbAi_thumbnail.webp",
    previewImage: [
      "/images/previewImage/mlbAi_previewimage1.webp",
      "/images/previewImage/mlbAi_previewimage2.webp",
      "/images/previewImage/mlbAi_previewimage3.webp",
      "/images/previewImage/mlbAi_previewimage4.webp",
    ],
    tags: ["Python", "Django", "AWS Lambda", "Supabase"],
    details: {
      overviews: [
        "大谷翔平選手のニュース・動画・成績を自動で収集・要約するLINE対応チャットボットです。",
        "収集データはLLMで要約・保存し、RAG構成で質問に自然に回答します。ファンキャラ「ラグ子」として、大谷選手について楽しく会話できます。",
      ],
      features: [
        "大谷翔平選手のニュース・動画・試合成績を毎日自動で収集・要約",
        "要約結果は「意味検索」できる形式でデータベースに保存",
        "検索結果をもとに、AIが自然な回答を生成",
        "情報収集と質問応答の2つのシステムで構成されたRAGチャットボット",
      ],
      technologies: [
        "Python",
        "Django",
        "PostgreSQL",
        "AWS Lambda",
        "OpenAI API",
        "LINE API",
        "Railway",
      ],
      github: "https://github.com/hiro774/mlbai",
      website: "",
    },
  },
  {
    id: 2,
    title: "Pomo - ポモドーロタイマー -",
    description: "Youtube動画をBGMに設定できるポモドーロアプリ",
    thumbnail: "/images/thumbnail/pomo_thumbnail.webp",
    previewImage: [
      "/images/previewImage/pomo_previewimage1.webp",
      "/images/previewImage/pomo_previewimage2.webp",
      "/images/previewImage/pomo_previewimage3.webp",
      "/images/previewImage/pomo_previewimage4.webp",
    ],
    tags: ["TypeScript", "Next.js", "Supabase"],
    details: {
      overviews: [
        "ポモドーロテクニックを実践するための、シンプルで使いやすいタイマーアプリです。",
        "作業・休憩時間の設定や、YouTubeを使ったBGM再生、ダークモードの切り替えなどに対応しています。Google認証によるログインや、ユーザーごとの設定保存機能も備えています。",
      ],
      features: [
        "作業・休憩時間を自由に設定可能",
        "タイマーの自動切り替えと進捗バー表示",
        "YouTubeで作業・休憩時間のBGM設定",
        "Google認証によるログイン対応",
        "各ユーザーの設定内容はSupabaseに保存＆自動読み込み",
      ],
      technologies: [
        "TypeScript",
        "React",
        "Next.js",
        "Tailwind CSS",
        "Supabase",
      ],
      github: "https://github.com/hiro774/pomo",
      website: "https://pomo-gamma-ashy.vercel.app/",
    },
  },
  {
    id: 1,
    title: "HIRO LAB",
    description: "制作実績・技術記事・AIチャットをまとめたポートフォリオサイト",
    thumbnail: "/images/previewImage/hirolab_home_2026_09.webp",
    previewImage: [
      "/images/previewImage/hirolab_home_2026_09.webp",
      "/images/previewImage/hirolab_about_2026_09.webp",
      "/images/previewImage/hirolab_articles_2026.webp",
      "/images/previewImage/hirolab_ai_2026.webp",
    ],
    tags: ["TypeScript", "Next.js", "Python", "FastAPI"],
    details: {
      overviews: [
        "開発経験や制作物、日々の学びをまとめたポートフォリオサイトです。",
        "ロボットをモチーフにしたデザインで、制作実績からプロフィール・技術記事・AIチャットへ進める、スマートフォン対応の画面構成にしています。",
      ],
      features: [
        "トップページでの最新3作品の紹介と、画像ギャラリー付きの制作実績詳細",
        "プロフィールと使用技術の紹介",
        "Zenn・Qiitaの記事一覧とキーワード検索",
        "OpenAI APIを活用した「HIRO AI」チャットと質問例からの入力",
        "送信結果を確認できるお問い合わせフォーム",
      ],
      technologies: [
        "TypeScript",
        "React",
        "Next.js",
        "Tailwind CSS",
        "Python",
        "FastAPI",
        "OpenAI API",
      ],
      github: "https://github.com/hiro774/hirolab",
      website: "https://hirolab.vercel.app/",
    },
  },
];
